config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :personas
  devise_for :users
  root to: 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  mount_uploader :file_appeal, FileAppealUploader
  
  validates :name,presence: true
  validates :address,presence: true
  validates :duration_time,presence: true
  validates :max_people,presence: true
  validates :ticket_value,presence: true

end

app/models/persona.rb
class Persona < ApplicationRecord
  belongs_to :user
  validates :name,presence: true
  validates :cnpj,presence: true
  validates :social_reason,presence: true
  validates :fantasy_name,presence: true
  validate :validate_one_guy

  def validate_one_guy
  	if Persona.where(user: self.user).size > 0
  		errors.add(:user, "Só pode haver um cadastro com seu usuário")
  	end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :persona
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @q = Event.ransack(params[:q])
    @events = @q.result.where(user: current_user).order(name: :desc).page(params[:page]).per(8)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :address, :duration_time, :max_people, :ticket_value,:file_appeal, :user_id)
    end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.where(user: current_user)
  end

  # GET /personas/1
  # GET /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)
    @persona.user_id = current_user.id
    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'Persona was successfully created.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'Persona was successfully updated.' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'Persona was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:name, :cnpj, :social_reason, :fantasy_name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="box">
    <div class="field">
      <label class="label">Nome</label>
      <div class="control">
        <%= f.input :name,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
    <div class="field">
      <label class="label">Endereço</label>
      <div class="control">
        <%= f.input :address,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
    <div class="field">
      <label class="label">Tempo de duração</label>
      <div class="control">
        <%= f.input :duration_time,label: false ,html5: true,input_html: {class: 'input'}%>
      </div>
    </div>
    <div class="field">
      <label class="label">Número Máximo de Pessoas</label>
      <div class="control">
        <%= f.input :max_people,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
    <div class="field">
      <label class="label">Valor do Ingresso</label>
      <div class="control">
        <%= f.input :ticket_value,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
    <div class="field">
      <label class="label">Foto do Ingresso</label>
      <div class="control">
        <%= f.input :file_appeal,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
  </div>

  <div class="control">
    <%= f.button :submit,class: "button is-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<article class="message is-dark">
	<div class="message-header">
		<p>Editar o Evento</p>
	</div>
 </article>
<%= render 'form', event: @event %>

<br>
<%= link_to 'Mostrar', @event ,class: "button is-info"%> 
<%= link_to 'Voltar', events_path ,class: "button is-link"%>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<article class="message is-dark">
  <div class="message-header">
    <p>Eventos Cadastrados</p>
  </div>
 </article> 

  <div class="box">
   <div class="field is-horizontal">
     <%= search_form_for @q do |f| %>

     <div class="field-body">
       <div class="field">
         <label class="label">Nome</label>
         <div class="control">
           <%= f.search_field :name_cont,label: false ,class: 'input'%>
         </div>
       </div>
       <div class="field">
         <label class="label">Valor do Ingresso</label>
         <div class="control">
           <%= f.search_field :ticket_value_eq,label: false ,class: 'input'%>
         </div>
       </div>
       <div class="field">
         <label class="label">Endereço</label>
         <div class="control">
           <%= f.search_field :address_cont,label: false ,class: 'input'%>
         </div>
       </div>
       <div class="field">
         <label class="label">Numéro Max. de pessoas</label>
         <div class="control">
           <%= f.search_field :max_people_eq,label: false ,class: 'input'%>
         </div>
       </div>
     </div>
     <br>
   </div>
 </div>
  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <div class="control">
          <%= f.submit class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
 <% end %>
 <br>
 <div class="columns is-gapless is-multiline is-mobile">
  <%= paginate @events %>
</div>
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Duração</th>
      <th>Número Máximo de pessoas</th>
      <th>Valor do Ingresso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.address %></td>
        <td><%= event.duration_time.to_s(:time) %></td>
        <td><%= event.max_people %></td>
        <td><%= event.ticket_value %></td>
        <td>
        <%= render 'shared/action_links', object: event %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Evento', new_event_path ,class: "button is-info"%>

app/views/events/new.html.erb
<article class="message is-dark">
	<div class="message-header">
		<p>Novo Evento</p>
	</div>
 </article>
<%= render 'form', event: @event %>

<br>
<%= link_to 'Voltar', events_path,class: "button is-link" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <header class="card-header">
    <p class="card-header-title">
    <%= @event.name %>
    </p>
  </header>
  <div class="card-content">
    <p class="card-header-title">
  Endereço: </p><%= @event.address %>
    <p class="card-header-title">: Duração</p><%= @event.duration_time.to_s(:time) %>
  </div>
    <% if @event.file_appeal.present?%>
      <%= image_tag(@event.file_appeal.url) %>
    <% end %>
  <footer class="card-footer">
    <%= link_to 'Editar', edit_event_path(@event),class: "card-footer-item" %>
    <%= link_to 'Voltar', events_path,class: "card-footer-item"%>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Appeal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag 'event.ico', :rel => 'shortcut icon' %>

  </head>
  
  <body>
    <nav class="navbar">
         <div class="container">
             <div class="navbar-brand">
                <%= link_to events_path,class: "navbar-item" do%>
                      Evento Do Roshan
                    <% end %>

                    <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                      <span aria-hidden="true"></span>
                    </a>
             </div>
             <div class="navbar-menu" id="navMenu">
                 <div class="navbar-end">
                    <%= link_to("Eventos", events_path ,class: "navbar-item") %>
                    <% if current_user.present? %>
                      <%= link_to("Meu perfil", personas_path,class: "navbar-item") %>
                      <span class="navbar-item"><%=current_user.email %></span>
                        <div class="navbar-item has-dropdown is-hoverable">
                            <%= link_to('Sair'.html_safe,  destroy_user_session_path , method: 'delete',class: 'navbar-link')%>
                        </div>
                    <% end %>
                 </div>
             </div>
         </div>
    </nav>

    <div class="container">
        <div id="flow">
            <span class="flow-1"></span>
            <span class="flow-2"></span>
            <span class="flow-3"></span>
        </div>
        <div class="section">
              <%= yield %>
      </div>
    </div>

  </body>
</html>

<script type="text/javascript">
  $(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});

</script>

app/views/personas/_form.html.erb
<%= simple_form_for(@persona) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <%= f.error_notification message: f.object.errors[:user].to_sentence if f.object.errors[:user].present?%>  

  <div class="box">
    <div class="field">
      <label class="label">Nome</label>
      <div class="control">
        <%= f.input :name,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>

    <div class="field">
      <label class="label">CNPJ</label>
      <div class="control">
        <%= f.input :cnpj,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>

    <div class="field">
      <label class="label">Razão Social</label>
      <div class="control">
        <%= f.input :social_reason,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>

    <div class="field">
      <label class="label">Nick ou nome fictício</label>
      <div class="control">
        <%= f.input :fantasy_name,label: false ,input_html: {class: 'input'}%>
      </div>
    </div>
  </div>

  <div class="control">
    <%= f.button :submit,class: "button is-primary" %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<article class="message is-dark">
	<div class="message-header">
		<p>Editar o Cadastro</p>
	</div>
 </article>
 <%= render 'form', persona: @persona %>
<br>
<%= link_to 'Mostrar', @persona ,class: "button is-info"%> 
<%= link_to 'Voltar', personas_path ,class: "button is-link"%>

app/views/personas/index.html.erb
<p id="notice"><%= notice %></p>

<article class="message is-dark">
  <div class="message-header">
    <p>Dados Pessoais</p>
  </div>
 </article> 

 <br>

<table class="table is-narrow">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cnpj</th>
      <th>Razão Social</th>
      <th>Nick</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
        <td><%= persona.name %></td>
        <td><%= persona.cnpj %></td>
        <td><%= persona.social_reason %></td>
        <td><%= persona.fantasy_name %></td>
        <td>
          <%= render 'shared/action_links', object: persona %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cadastro', new_persona_path ,class: "button is-info"%>

app/views/personas/new.html.erb
<article class="message is-dark">
	<div class="message-header">
		<p>Novo Cadastro de Dados Pessoais</p>
	</div>
 </article>
	<%= render 'form', persona: @persona %>
<br>
<%= link_to 'Voltar', personas_path,class: "button is-link" %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card">
  <header class="card-header">
    <p class="card-header-title">
    <%= @persona.name %>
    </p>
  </header>
  <div class="card-content">
    <p class="card-header-title">
  CNPJ: </p><%= @persona.cnpj %>
    <p class="card-header-title">: Razão Social</p><%= @persona.social_reason %>
  </div>
  <footer class="card-footer">
    <%= link_to 'Editar', edit_persona_path(@persona),class: "card-footer-item" %>
    <%= link_to 'Voltar', personas_path,class: "card-footer-item"%>
  </footer>
</div>

app/views/shared/_action_links.html.erb
<%= link_to object, data: { toggle: 'tooltip', placement: 'top', title: 'Visualizar' }, class: 'button is-primary' do %>
  <i class="fa fa-eye"></i>
<% end %>
&nbsp;

<%= link_to eval("edit_#{object.class.to_s.underscore}_path(#{object.id})"), data: { toggle: 'tooltip', placement: 'top', title: 'Editar' }, class: 'button is-warning' do %>
  <i class="fa fa-pencil"></i>
<% end %>
&nbsp;
<%= link_to object, method: :delete, data: { confirm: 'Tem certeza?', toggle: 'tooltip', placement: 'top', title: 'Apagar' }, class: 'button is-danger' do %>
  <i class="fa fa-trash"></i>
<% end %>